<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arrow Kanan Artikel Terbaru</name>
   <tag></tag>
   <elementGuidId>5a46eb7d-9e78-4387-ba17-f23068d76e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.js-slider-new-article-prev.swiper-button-disabled > div.img-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main/div[3]/div/div/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cf48c70-0a19-4d08-8f71-a4b4ab99b4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow</value>
      <webElementGuid>68e36d85-15f0-4a02-8cc2-56af932a2e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;pimcore_area_home-new-article pimcore_area_content&quot;]/div[@class=&quot;article-new sect&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;js-slider-new-article-prev swiper-button-disabled&quot;]/div[@class=&quot;img-arrow&quot;]</value>
      <webElementGuid>1826c5ee-16f1-4e39-ac6b-3a609f62920c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[3]/div/div/div[4]/div/div</value>
      <webElementGuid>5d0d225a-598f-4df5-a783-0037f42a0aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
