<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bebeclub logo</name>
   <tag></tag>
   <elementGuidId>8e2cbb2a-a470-4a21-94dc-6af6991589b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='bebelac']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>860a9c34-12a8-4e21-a2ee-8db0d205211c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png</value>
      <webElementGuid>779b03fc-059d-43b8-849b-74a2de8a7fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ls-is-cached lazyloaded</value>
      <webElementGuid>779d72b8-6a8d-4323-b5cd-10530b380691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>bebelac</value>
      <webElementGuid>2a135249-b6b7-4cf4-9704-4eba453a70f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>bebelac</value>
      <webElementGuid>432046be-e24d-445d-a92b-7a449a7fcefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>133px</value>
      <webElementGuid>566092d2-60e5-43ab-a890-ae5feaca11ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35px</value>
      <webElementGuid>064102be-0771-493d-bbaa-8d8181ffb216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png</value>
      <webElementGuid>d7e235df-7f20-44f5-b363-a883edadaf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>1980770380</value>
      <webElementGuid>9ea8c93b-d51c-43ab-b8f9-309ee3ebeb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>9258e1c1-ce3b-4d00-8f42-e5c50fe3e607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;headers-menu&quot;]/div[@class=&quot;headers-menu_iner&quot;]/div[@class=&quot;container_fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;headers-menu_logo&quot;]/a[@class=&quot;headers-menu_brand&quot;]/picture[1]/img[@class=&quot;ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>439680c5-6dc6-4b55-8a8f-42c1c440c6ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='bebelac']</value>
      <webElementGuid>73bf317c-95b6-478d-a724-80ce24a29ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2c317047-5024-48a0-8915-d1b009410042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'bebelac' and @title = 'bebelac' and @src = 'https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png']</value>
      <webElementGuid>8ab11330-ad0d-4758-af76-398e964a2071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
