<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonLoginTanpaPassword</name>
   <tag></tag>
   <elementGuidId>643b6d17-480c-4aac-8de9-a3ce7e2a2324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loginotpcta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginotpcta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>411d8a28-f9e4-419f-b715-29a2ae549719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/membership/login-otp</value>
      <webElementGuid>f03a6c33-2180-48ce-a469-da92c40499fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn --primary-reverse loginotpcta</value>
      <webElementGuid>3df1fede-b22c-49f1-9793-778b110e1b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginotpcta</value>
      <webElementGuid>7d4ef2eb-8fe8-40f7-8113-e584b1e28bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Tanpa Password</value>
      <webElementGuid>b93c2702-5aee-4777-97cb-ce0370fbb5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginotpcta&quot;)</value>
      <webElementGuid>11c94eb8-3ed0-4333-99c1-2cf3bced9994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='loginotpcta']</value>
      <webElementGuid>fd87e2d2-0c29-4bb7-8d20-bc0f45c4f30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-login-password']/div[5]/a</value>
      <webElementGuid>268d75c6-0dd3-49ad-9bff-3017f276b159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login Tanpa Password')]</value>
      <webElementGuid>651a5d5c-1230-4efd-b0cf-dc9bead20529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[1]</value>
      <webElementGuid>c6ddaef1-affa-4184-b3ca-b2986adc597e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/following::a[1]</value>
      <webElementGuid>2f30fef1-f2ac-41e3-9263-55ed7bb98997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Berhasil'])[1]/preceding::a[1]</value>
      <webElementGuid>39cbdfd8-de3e-4820-8ecf-57941d0ed017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat profil saya'])[1]/preceding::a[1]</value>
      <webElementGuid>d9549af3-d2df-440d-924c-aa3ab79c2ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login Tanpa Password']/parent::*</value>
      <webElementGuid>bd85a550-8ea2-4d29-8b2d-0be853a2dcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/membership/login-otp')]</value>
      <webElementGuid>3510d2a6-be63-4cde-bfa4-6bf62764693f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/a</value>
      <webElementGuid>4dd58bba-6b5f-41d2-9284-14e1ae8da4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/membership/login-otp' and @id = 'loginotpcta' and (text() = 'Login Tanpa Password' or . = 'Login Tanpa Password')]</value>
      <webElementGuid>4588e21d-a0ad-41f3-8745-8ecbd7f1a3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
