<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Banner Arrow Right</name>
   <tag></tag>
   <elementGuidId>9fc66957-b63a-4a2b-b57c-d3001d0ac727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div[3]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.img-arrow.right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8bdc03b2-da64-4dd5-bc08-984c29f153f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow right</value>
      <webElementGuid>5d9264d9-504c-49bb-8dac-cf1fd2b758a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;container button-icon&quot;]/div[@class=&quot;js-slider-hero-next swiper-button-disabled&quot;]/div[@class=&quot;img-arrow right&quot;]</value>
      <webElementGuid>8ae21df7-f664-464f-9377-47c69ee5630b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[2]/div</value>
      <webElementGuid>914ab497-57e1-467b-adbf-26de5ce6bf59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
