<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>0aa02148-fdc4-4114-8852-fcd47634a24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ecommModalTrigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ecommModalTrigger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38341b87-2203-4ef7-9af2-07d7f12c9a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn beli-sekarang__button ecommModalTrigger</value>
      <webElementGuid>047a5ca8-417e-4dd1-ac2d-1de10b537675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ecommModalTrigger</value>
      <webElementGuid>52428a04-afd6-480e-83ce-0a954402ac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>fd589213-378c-492c-8dd8-e9fabcb001cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-product pimcore_area_content&quot;]/div[@class=&quot;product-homepage&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-homepage_content&quot;]/div[@class=&quot;product-homepage-list-item&quot;]/div[@class=&quot;ecomm&quot;]/div[@class=&quot;beli-sekarang&quot;]/button[@id=&quot;ecommModalTrigger&quot;]</value>
      <webElementGuid>af5c84e7-f335-484d-8d38-d780a1441dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ecommModalTrigger']</value>
      <webElementGuid>1134886e-48a0-4925-8d60-0720b6e45b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Usia 1-3 Tahun'])[1]/following::button[1]</value>
      <webElementGuid>c3eb73de-4ce5-472a-a86e-46070502ad44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebelac 3'])[3]/following::button[1]</value>
      <webElementGuid>8e9016d8-a2c0-4ea5-8ef7-89a7ebd3a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebelac 3'])[4]/preceding::button[1]</value>
      <webElementGuid>97019657-1523-4353-8064-edd3f3ea20a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>2e296c17-8a96-469f-803f-203b6dd11e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8eaac24a-50e9-486b-a8cf-25945e5379e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ecommModalTrigger' and (text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>c1bb5061-f61a-495c-bd05-1d44f3cb3af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
