<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bebelac Gold Soya_headers-menu_search_icon</name>
   <tag></tag>
   <elementGuidId>94d09b67-be3e-4242-b21d-4f820acccd49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.headers-menu_search_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee28d52b-29f5-4f4e-9b9d-fb79661f1de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headers-menu_search_icon</value>
      <webElementGuid>72174b6b-f0c1-45e2-96d1-f13f32d87664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;headers-menu&quot;]/div[@class=&quot;headers-menu_iner&quot;]/div[@class=&quot;container_fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 hidden-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;headers-menu_search&quot;]/div[@class=&quot;headers-menu_search_icon&quot;]</value>
      <webElementGuid>1baab6de-b530-4a68-b8d3-a1405d2c4deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div</value>
      <webElementGuid>e43977de-c0f3-44fa-a7ee-d99a9b137271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
