<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lihat Detail_img-arrow</name>
   <tag></tag>
   <elementGuidId>ca0ea296-1681-4dcb-978b-7c816a986a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.js-slider-grogreat-prev > div.img-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>552067cc-d581-4483-a7a6-3b8fccbf4f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow</value>
      <webElementGuid>b64cdf42-ea78-4a11-ba56-0803596ef6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-gogreat-slide pimcore_area_content&quot;]/div[@class=&quot;home-gogreat-slider sect&quot;]/div[@class=&quot;slider-area&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;js-slider-grogreat-prev&quot;]/div[@class=&quot;img-arrow&quot;]</value>
      <webElementGuid>42967b25-5093-46ab-a5f0-a4cddac5f95d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
      <webElementGuid>38b2223d-8368-438d-986a-7876a45aa67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
