<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bebeclub Expert_img-arrow</name>
   <tag></tag>
   <elementGuidId>0b0ed0b9-2d26-4dec-9f67-3067d4735f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d9de4ab-8e29-4ad1-babb-2abcd22fff8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow</value>
      <webElementGuid>80c00dc3-4a40-458b-b9b9-0c7734e5b3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;container button-icon&quot;]/div[@class=&quot;js-slider-hero-prev&quot;]/div[@class=&quot;img-arrow&quot;]</value>
      <webElementGuid>2c962d99-1124-4c14-b0b7-8d3b1e466e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>dffe56c8-9bba-41f0-ab0a-f13875989cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
