<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bebelac dukung penuh ASI eksklusif_icon-arrow-down</name>
   <tag></tag>
   <elementGuidId>550129a0-5dcf-4e9e-b816-3b3f6512c3b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-arrow-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10110ff5-ccfc-4573-a6b8-c224043851ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-down</value>
      <webElementGuid>c23c93f5-efa9-4ccb-b7e2-9b3368a96c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_footer pimcore_area_content&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer-asi&quot;]/div[@class=&quot;container_fluid&quot;]/div[@class=&quot;footer-asi_label&quot;]/div[@class=&quot;icon-arrow-down&quot;]</value>
      <webElementGuid>89c852d7-113b-4ca6-8340-b6b54e6a2010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div</value>
      <webElementGuid>38bcefa2-2f24-4a25-a42a-41a60d4a081e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
