<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_082123458383</name>
   <tag></tag>
   <elementGuidId>3dd9b3ef-59fd-44ff-9b6e-64c1137a49e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Via Whatsapp'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fb904f4-84f5-49b3-863f-f23d7fafa9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 082123458383</value>
      <webElementGuid>9ddf60c2-df08-49e4-92e1-aede0290d92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_footer pimcore_area_content&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer-iner&quot;]/div[@class=&quot;container_fluid&quot;]/div[@class=&quot;footer-iner_1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;footer-line-one_first&quot;]/a[2]/div[@class=&quot;footer-line-one_call&quot;]/div[1]/div[2]</value>
      <webElementGuid>f57c221c-afa3-4091-88ba-37b5eaf93930</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Via Whatsapp'])[1]/following::div[1]</value>
      <webElementGuid>3353d69d-b937-4365-b5c1-11815e19b9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Via Telp (bebas biaya)'])[1]/following::div[5]</value>
      <webElementGuid>c1907757-86c8-46fb-abda-14d8619ad619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2023 Bebelac.'])[1]/preceding::div[11]</value>
      <webElementGuid>92afd5e4-2d24-4af0-b3cd-b147d97fe2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta situs'])[1]/preceding::div[12]</value>
      <webElementGuid>57903467-8020-4e0f-9f45-7c2875e9ef8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='082123458383']/parent::*</value>
      <webElementGuid>a099046e-bd42-4796-aacb-0404b17bb12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/div[2]</value>
      <webElementGuid>54017634-ca8f-4a20-b6a0-63a30c6284b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 082123458383' or . = ' 082123458383')]</value>
      <webElementGuid>ce6258a1-3b8b-473e-b42f-61ed3736b015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
