<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Temukan Inspirasi Seputar Nutrisi dan_headers-menu_search_icon</name>
   <tag></tag>
   <elementGuidId>ad2b6a6a-4884-4edb-8925-a8db9088f5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-after_banner_input > div.headers-menu_search > div.headers-menu_search_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1dcb738e-d9f4-452f-9507-1c2729bb91af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headers-menu_search_icon</value>
      <webElementGuid>cd9767aa-ed0d-4927-b263-fcbc32f3359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-search pimcore_area_content&quot;]/div[@class=&quot;search-after_banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;search-after_banner_input&quot;]/div[@class=&quot;headers-menu_search&quot;]/div[@class=&quot;headers-menu_search_icon&quot;]</value>
      <webElementGuid>4410ba76-1d77-4165-96c1-d2b27c5c4051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>52b0262d-65af-49ef-9a22-d085c2ed1497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
