<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Beli</name>
   <tag></tag>
   <elementGuidId>c1a767ee-25bf-445b-a8eb-e4379ce0de71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.beli-sekarang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Usia 1-3 Tahun'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98e6c018-9d6a-4192-aa6e-dcc5659f49bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>beli-sekarang</value>
      <webElementGuid>b121e74c-9e30-49b8-a388-2dc089dc7933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Beli
</value>
      <webElementGuid>1d304923-ce2b-41e9-80c1-17fdf2d4c760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-product pimcore_area_content&quot;]/div[@class=&quot;product-homepage&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-homepage_content&quot;]/div[@class=&quot;product-homepage-list-item&quot;]/div[@class=&quot;ecomm&quot;]/div[@class=&quot;beli-sekarang&quot;]</value>
      <webElementGuid>0f8fcddc-b461-492b-8a7d-1b398f44ce35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk Usia 1-3 Tahun'])[1]/following::div[2]</value>
      <webElementGuid>c6b2dd9a-7770-49de-a0a2-309884546ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebelac 3'])[3]/following::div[2]</value>
      <webElementGuid>140d0dcd-3ba0-490e-9871-0d5834943dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div</value>
      <webElementGuid>651cc3b7-59db-4a0f-acef-924d1450668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
Beli
' or . = '
Beli
')]</value>
      <webElementGuid>1eef6c94-62bf-4dda-9a95-1fb1e41fc3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
