<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bebeclub Expert_img-arrow right</name>
   <tag></tag>
   <elementGuidId>36d1c4a7-3481-4bb0-a76e-c7d128d3d554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-arrow.right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a6202be-f613-4d32-9b2b-af8b2dc1aa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow right</value>
      <webElementGuid>5ddad799-1df8-41a4-a9e8-38c51e13c9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;container button-icon&quot;]/div[@class=&quot;js-slider-hero-next&quot;]/div[@class=&quot;img-arrow right&quot;]</value>
      <webElementGuid>4c23061b-2340-4a29-8983-b1a07471abd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>d661671a-e82c-4e2b-afe5-01011e6d54fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
