<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terbaru_card-thumb_img</name>
   <tag></tag>
   <elementGuidId>473994a6-fc5f-4877-a347-eddee6811072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-thumb_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Terbaru'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e69659c-e559-4a5b-abc8-0f0c642f1ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-thumb_img</value>
      <webElementGuid>94f3f42f-4ca6-4042-ac7f-53d8be4313ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-new-article pimcore_area_content&quot;]/div[@class=&quot;article-new sect&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;article-new_content&quot;]/div[@class=&quot;slider-new-article swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;card-thumb&quot;]/a[1]/div[@class=&quot;card-thumb_img&quot;]</value>
      <webElementGuid>e8b20d54-5db5-4f8e-84b3-eef9e4d5d30f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terbaru'])[1]/following::div[6]</value>
      <webElementGuid>d7eeb808-f3b1-4a3e-bf81-4e8615dacd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ibu Perlu Tahu'])[3]/preceding::div[2]</value>
      <webElementGuid>08626517-b070-4c86-bb45-c9c1593cc4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ibu tandai artikel ini saran informatif'])[1]/preceding::div[3]</value>
      <webElementGuid>a0689424-67dc-4900-aeae-07bf59ecc334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/div</value>
      <webElementGuid>6c6d8792-2f41-4a89-9b37-4023d92e2c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
