<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bebeclub Expert_banner-desktop ls-is-cached lazyloaded</name>
   <tag></tag>
   <elementGuidId>060bff51-84d0-4fb1-9ab2-b8006f49837f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.swiper-slide.swiper-slide-active > div > picture > img.banner-desktop.ls-is-cached.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='homepage-banner'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>474afa1d-9725-4945-86c1-59da5413a642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/FA_BB4_Homepage%20Banner_Desktop%20%281%29.webp</value>
      <webElementGuid>a8bf800d-b03c-4ad2-9978-85df3b25bbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-desktop ls-is-cached lazyloaded</value>
      <webElementGuid>37bb122c-ac5c-43b1-b54a-be1e0a2307c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>homepage-banner</value>
      <webElementGuid>21f02ab1-ce1d-49ed-ac59-ac960bed7a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>homepage-banner</value>
      <webElementGuid>eb68ffe3-11f0-4423-815a-8068364e314f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1440px</value>
      <webElementGuid>39378b04-91b3-4ee8-b9c2-7d4c3123fbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>768px</value>
      <webElementGuid>950021a6-98d5-4526-8ec7-cd4fc0aed1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/FA_BB4_Homepage%20Banner_Desktop%20%281%29.webp</value>
      <webElementGuid>d7ed33e9-49b9-497b-9f53-61ec3284d13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;swiper-wrapper&quot;]/a[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[1]/picture[1]/img[@class=&quot;banner-desktop ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>cbb854d1-5862-4125-b5d5-ce457c7dbfe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='homepage-banner'])[5]</value>
      <webElementGuid>c0fb8344-c247-465c-b3ff-0bb1bd1893dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/div/picture/img</value>
      <webElementGuid>01b777d1-40b6-4a3f-8eb5-309645453c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'homepage-banner' and @title = 'homepage-banner' and @src = 'https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/FA_BB4_Homepage%20Banner_Desktop%20%281%29.webp']</value>
      <webElementGuid>259bbddd-bf54-4cc1-bf2c-8023f72e98dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
