<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bebelac</name>
   <tag></tag>
   <elementGuidId>0a9eeffa-d74e-41b4-a324-68b46395afee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='bebelac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c661475-1672-4655-975c-04968d32a350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png</value>
      <webElementGuid>3142156f-1b21-4065-a09a-5c76fe8f1d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ls-is-cached lazyloaded</value>
      <webElementGuid>164020a0-d098-4aff-a116-9f898f4b543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>bebelac</value>
      <webElementGuid>d0151e0d-4b92-4aaf-ba98-a96d94c53d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>bebelac</value>
      <webElementGuid>e0296d8f-c80e-41a7-9934-dbacc92c9e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>133px</value>
      <webElementGuid>a00ddf56-c548-4cce-9250-7a3739e826b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35px</value>
      <webElementGuid>e1b967f0-aea4-4140-9ab9-047822e5bdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png</value>
      <webElementGuid>3c87a3ba-6157-40d4-bab5-0ea9db600cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;headers-menu&quot;]/div[@class=&quot;headers-menu_iner&quot;]/div[@class=&quot;container_fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;headers-menu_logo&quot;]/a[@class=&quot;headers-menu_brand&quot;]/picture[1]/img[@class=&quot;ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>19289a5f-7a37-41ea-893b-36ffe543327a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='bebelac']</value>
      <webElementGuid>8543ccbf-9f2c-431e-84b4-d69a7152d7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f6588e6c-cc84-45c7-b174-2740e68951fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'bebelac' and @title = 'bebelac' and @src = 'https://d24eqpince6acm.cloudfront.net/assets/images/logo/logo.png']</value>
      <webElementGuid>7d1c2054-f70d-4e83-83b0-887cc32bddf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
