<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Beli Produk_lazyloaded</name>
   <tag></tag>
   <elementGuidId>7be90acf-1e0f-494a-9d5d-87b9d70de572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d24eqpince6acm.cloudfront.net/_default_upload_bucket/other-product-bebe-gold-soya%20%281%29_3.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a605ce84-710b-4a3e-8a75-82ac5a6ab46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0569d44d-e3b7-4e69-a9c6-f11e8c74430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>126px</value>
      <webElementGuid>f0200a2d-fdc1-41e2-9370-f8805b0c2336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160px</value>
      <webElementGuid>b53b2f38-b249-4345-a55d-d3f81f6fecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
      <webElementGuid>2def4cfc-9d2a-4cdb-aede-fff9100559ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/_default_upload_bucket/other-product-bebe-gold-soya%20%281%29_3.webp</value>
      <webElementGuid>aa1211f4-b49a-4db4-8c73-d322635bf464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/_default_upload_bucket/other-product-bebe-gold-soya%20%281%29_3.webp</value>
      <webElementGuid>21fc49b2-6660-4b00-8027-37d45da7e4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-product pimcore_area_content&quot;]/div[@class=&quot;product-homepage&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-homepage_content&quot;]/div[@class=&quot;product-homepage-list-item&quot;]/a[@class=&quot;product-homepage_content_card&quot;]/div[1]/picture[1]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>e37f638d-5ca8-4292-98cf-5955c1bed6b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d24eqpince6acm.cloudfront.net/_default_upload_bucket/other-product-bebe-gold-soya%20%281%29_3.webp')]</value>
      <webElementGuid>0b1711df-5565-4f7b-9be0-cd966cfdc882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/picture/img</value>
      <webElementGuid>ed00d4ad-39a9-4466-9577-de45225fbb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d24eqpince6acm.cloudfront.net/_default_upload_bucket/other-product-bebe-gold-soya%20%281%29_3.webp']</value>
      <webElementGuid>d2c3acc1-1374-41c0-8f70-fad0c412311f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
