<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_di Setiap Tahapan Usia Anak Hebat_lazyloaded</name>
   <tag></tag>
   <elementGuidId>f5ac6cf8-8abe-441e-96f2-e83ced72bd9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Bebelac-3_3kg_front_vanila%20%281%29.webp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c156a712-1c93-4541-9d68-8cb9b3f20d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cf9621f8-d5dc-4698-8ad1-b0574eea896e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>126px</value>
      <webElementGuid>0e007695-4f4d-4f68-baeb-a5064b13ede6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160px</value>
      <webElementGuid>963f25e8-e00a-4a98-9cb1-4b64c53f5bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
      <webElementGuid>8c26a915-7626-4448-8389-a027d26ec360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Bebelac-3_3kg_front_vanila%20%281%29.webp</value>
      <webElementGuid>2b7b2575-b615-41e4-909c-d278570dd717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Bebelac-3_3kg_front_vanila%20%281%29.webp</value>
      <webElementGuid>f12c6bed-4071-422d-9f88-3ba3e1d2bb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-product pimcore_area_content&quot;]/div[@class=&quot;product-homepage&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-homepage_content&quot;]/div[@class=&quot;product-homepage-list-item&quot;]/a[@class=&quot;product-homepage_content_card&quot;]/div[1]/picture[1]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>e5a8dc3d-f598-4946-8a92-daca87ae220e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Bebelac-3_3kg_front_vanila%20%281%29.webp')]</value>
      <webElementGuid>3b6d7993-befa-40ea-92b5-69b0fc998a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/a/div/picture/img</value>
      <webElementGuid>bf8179cc-bc3a-46b2-9dae-c4ec0a81dbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Bebelac-3_3kg_front_vanila%20%281%29.webp']</value>
      <webElementGuid>ca7d7956-69f1-49e2-87d2-18c603eac40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
