<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lihat Detail_banner-desktop ls-is-cached lazyloaded</name>
   <tag></tag>
   <elementGuidId>465ba514-e4a0-4375-b59b-2b7807898fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-next > a > div.tools-card > div.tools-card_img > picture > img.banner-desktop.ls-is-cached.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='tools bebeclub'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8fdc9c4b-7688-4a5b-96bd-974033e73574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>136653e6-55b2-42d9-81f2-ac09e406e17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-desktop ls-is-cached lazyloaded</value>
      <webElementGuid>a64ba0d0-e8d7-4e0a-952a-6a05b535224f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>tools bebeclub</value>
      <webElementGuid>ef0a2705-3ff2-4208-b340-eab0097c61be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>155px</value>
      <webElementGuid>b60f68b0-bc6d-4be6-9c46-dd2b016830a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>130px</value>
      <webElementGuid>3d2897f7-3d80-48e6-9338-bd753fba8f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Desktop%20-%20Partner%20Terpercaya_4.webp</value>
      <webElementGuid>2596c301-34c0-40cd-bf46-7e05a3cb2e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Desktop%20-%20Partner%20Terpercaya_4.webp</value>
      <webElementGuid>7fc30c8a-0539-4b1e-9848-a92a038a815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-tools pimcore_area_content&quot;]/div[@class=&quot;tools-ibu-hebat sect&quot;]/div[1]/div[@class=&quot;tools-ibu-hebat_content&quot;]/div[@class=&quot;slider-tools-ibu swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/a[1]/div[@class=&quot;tools-card&quot;]/div[@class=&quot;tools-card_img&quot;]/picture[1]/img[@class=&quot;banner-desktop ls-is-cached lazyloaded&quot;]</value>
      <webElementGuid>ebbb31f2-2efa-4c7b-ba5d-c046ca9476bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='tools bebeclub'])[8]</value>
      <webElementGuid>09a57a01-c272-4050-96ae-086e0aa06d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/div/div/picture/img</value>
      <webElementGuid>59ea9d02-4fa7-4417-9d25-5ebb4f1ec3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'tools bebeclub' and @src = 'https://d24eqpince6acm.cloudfront.net/Artikel/Slider%20Home/Desktop%20-%20Partner%20Terpercaya_4.webp']</value>
      <webElementGuid>c645570e-182e-435d-8c46-9fe3702b49e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
