<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bebeclub Expert_swiper-pagination-bullet swiper-pagination-bullet-active</name>
   <tag></tag>
   <elementGuidId>f6255d45-93fa-421e-a5b6-12ccd7d58a15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.swiper-pagination-bullet.swiper-pagination-bullet-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1dcc0f1-2b05-4f83-8c34-101a5bc088a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-pagination-bullet swiper-pagination-bullet-active</value>
      <webElementGuid>d7ef76f5-7617-4d64-9612-b4136bb038e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;swiper-hero-pagination swiper-pagination-clickable swiper-pagination-bullets&quot;]/span[@class=&quot;swiper-pagination-bullet swiper-pagination-bullet-active&quot;]</value>
      <webElementGuid>3aa3b779-d53c-4222-8f40-6805086c5058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>cc6e5857-ac9c-4235-a934-67f7a3e62d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
