<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bebeclub Expert_swiper-pagination-bullet</name>
   <tag></tag>
   <elementGuidId>3f407d7c-7b34-4047-98cc-aaea436a9cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>312b6a8e-13dd-471a-bca6-3176ae994a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-pagination-bullet</value>
      <webElementGuid>d55d8a0a-381e-413e-9d76-ea451696521f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_home-banner pimcore_area_content&quot;]/div[1]/div[@class=&quot;js-slider-hero swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;swiper-hero-pagination swiper-pagination-clickable swiper-pagination-bullets&quot;]/span[@class=&quot;swiper-pagination-bullet&quot;]</value>
      <webElementGuid>c411a8e7-a6ac-458d-88a8-363a50869c07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>91980b0a-22fb-492d-80a0-cc2ec2a0e919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
