<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Penulis</name>
   <tag></tag>
   <elementGuidId>a674d309-ac74-42d4-90ff-95978bbd1aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Penulis'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0abb4ae2-f046-4d86-bc2f-1f04d87b6a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penulis</value>
      <webElementGuid>8b8c7ad9-65e9-4241-b28d-88e59c2d077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;hero-contributor&quot;]/div[@class=&quot;hero-contributor__container&quot;]/div[@class=&quot;row profiledesc&quot;]/div[@class=&quot;col-12 col-md-12 sol-sm-12 col-lg-6 col-xl-6&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;hero-contributor__info&quot;]/div[1]/p[1]</value>
      <webElementGuid>a61895a1-43b6-44bb-83eb-4f41be8d62ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Penulis'])[1]/following::p[1]</value>
      <webElementGuid>fc4cb157-0c54-4c75-ada4-c0a5461f68ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::p[1]</value>
      <webElementGuid>12b52c05-cb0c-472a-babb-4f181d6cce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Febriyani Suryaningrum'])[1]/preceding::p[1]</value>
      <webElementGuid>29be8543-09d6-4e7f-b79e-3c765dcc0768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Profesional >'])[1]/preceding::p[1]</value>
      <webElementGuid>88490789-59f7-4f1e-8b60-f52bf5146780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penulis']/parent::*</value>
      <webElementGuid>8c1158f9-e2a3-4d9a-8904-8eb7c5b326d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>1e5513dd-fc37-40b4-9a19-2338e60a49cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Penulis' or . = 'Penulis')]</value>
      <webElementGuid>eb094cd4-937c-4963-8726-0e319a36da30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
