<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Sedang Hamil  Memiliki Anak</name>
   <tag></tag>
   <elementGuidId>5d59a15e-82b1-4b36-8888-9a584dbae637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@value='9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li[value=&quot;9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>91c17b76-55fb-4408-81ab-8a0b528897ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>992ed4f4-fb5c-4302-834c-2138e4883782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sedang Hamil &amp; Memiliki Anak</value>
      <webElementGuid>92239730-e666-48e4-95fc-6cdea4b52181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-status&quot;)/li[2]</value>
      <webElementGuid>e9217f5c-bdc1-4f25-b431-2216e16820c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@value='9']</value>
      <webElementGuid>303e01bd-2ce7-4ce5-b23d-783c84f38d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-status']/li[2]</value>
      <webElementGuid>388b9431-3788-45dd-8333-3ef3d0210cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Hamil'])[1]/following::li[1]</value>
      <webElementGuid>016d3f73-cc04-44c0-a7d1-f9c2f30a72da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi Mama saat ini'])[1]/following::li[2]</value>
      <webElementGuid>7b10b9be-b5de-4ca0-bf8e-824d32ddc6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Hamil &amp; Memiliki Anak'])[1]/preceding::li[1]</value>
      <webElementGuid>d92f6eac-eb45-433d-a24e-dc0a48f3933c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Hamil'])[1]/preceding::li[2]</value>
      <webElementGuid>cd88679a-5d50-40d1-9aa0-ea025ac27baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sedang Hamil &amp; Memiliki Anak']/parent::*</value>
      <webElementGuid>d87ebb1c-2fd4-4a61-8b00-1a57050b19de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[2]</value>
      <webElementGuid>5ee7f336-d7b8-4dd6-ba54-4f00e550fdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Sedang Hamil &amp; Memiliki Anak' or . = 'Sedang Hamil &amp; Memiliki Anak')]</value>
      <webElementGuid>b1e501ab-5f73-4706-856f-7f5b0b799d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
