<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bebejourney</name>
   <tag></tag>
   <elementGuidId>25be42bd-1f55-4841-8f64-3b738f1610d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sub-menu-mobile.opened > div.submenu-nav-item > a:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Bebejourney')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>382633b4-7dd1-4848-b5fd-079296e47848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tools/bebe-journey</value>
      <webElementGuid>b1224502-97b6-480c-85cf-4b9de0db6741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bebejourney</value>
      <webElementGuid>54950d52-1622-409e-b079-ee09c074706f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;headers-menu&quot;]/div[@class=&quot;headers-menu_mobile show-sm&quot;]/div[1]/div[@class=&quot;headers-menu_mobile_link menu-nav&quot;]/div[@class=&quot;menu-nav-item have-sub&quot;]/div[@class=&quot;sub-menu-mobile opened&quot;]/div[@class=&quot;submenu-nav-item&quot;]/a[3]</value>
      <webElementGuid>453c641a-63b7-46ff-bdfe-3c277a61f819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bebejourney')])[2]</value>
      <webElementGuid>75f6d4cb-2de9-4bc5-a257-056b21a4096a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tummypedia'])[2]/following::a[1]</value>
      <webElementGuid>f529ef11-1356-4260-9b4b-38557f0b7434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BebeStory'])[2]/following::a[2]</value>
      <webElementGuid>61257b3a-ab49-4036-8ae1-e21e54340b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergy Checker'])[2]/preceding::a[1]</value>
      <webElementGuid>37d2b724-3122-40c3-8dab-4f4f0073a6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo &amp; Event'])[2]/preceding::a[2]</value>
      <webElementGuid>55d5d362-aab1-42ba-b6d2-acbc33173930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tools/bebe-journey')])[2]</value>
      <webElementGuid>59052628-d2fc-468f-aea8-a43ea3e80620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[3]</value>
      <webElementGuid>9e5f6edd-4c4f-4364-9ecf-ec092fc596d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tools/bebe-journey' and (text() = 'Bebejourney' or . = 'Bebejourney')]</value>
      <webElementGuid>11f1c941-ef3c-4745-b599-c534db61e70f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
