<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Tim Ahli___st_preview_frame_bpn</name>
   <tag></tag>
   <elementGuidId>47d3d558-f303-45b4-9a81-c9dc9d86039d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.__st_preview_frame_bpn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__st_fancy_popup']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ba9c2bce-7f95-433a-ac94-fed0549eb1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__st_preview_frame_bpn</value>
      <webElementGuid>72f017ec-185f-4ac8-924b-080582aa182b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1b1966c9-42f0-40f0-91e9-6057bf762e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76d8b8b7-53a4-404f-905d-b201363a75c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_fancy_popup&quot;)/iframe[@class=&quot;__st_preview_frame_bpn&quot;]</value>
      <webElementGuid>bcdb440a-9476-40e7-9716-610bf427b610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__st_fancy_popup']/iframe</value>
      <webElementGuid>153c56f1-67d8-4a72-92b3-e5613e3a0254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/iframe</value>
      <webElementGuid>6579e1c5-1135-4cb4-b4c7-5c3edaeb7bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
