<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_syarat  ketentuan_a-f6hhmpiuub4a</name>
   <tag></tag>
   <elementGuidId>02ff1fda-0464-4ba9-afd5-e7841994d0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-f6hhmpiuub4a&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-f6hhmpiuub4a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>45ab4c04-f498-457e-bd45-5ed16dc778e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>15270a75-7e2c-4626-82e0-56b410f33b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>4f36c08b-ff02-40ec-b212-b04e19eb90a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e7c936e7-dd41-4cba-9ae5-a96d2948dd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>88369333-4d97-443d-98fc-7ff9bdcadd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-f6hhmpiuub4a</value>
      <webElementGuid>1f4a8c70-f21d-4e25-a604-dcca46bb139f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04a440f9-7fa5-4a33-8ba8-f18fa453d2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f5a2f3be-0858-4dbf-a692-b8ea18586c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>63440945-81fd-494a-bdc7-262b55a522e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcCBsYoAAAAAH229CaA_zpClCyFwuqQXZ9M5EmT&amp;co=aHR0cHM6Ly9iZWJlY2x1Yi5leWRlbmRpZ2l0YWwuY28uaWQ6NDQz&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=b1tjqahjrhfc</value>
      <webElementGuid>d579aa74-7c58-4c22-946a-e0d653d21217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-login&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>b00e99f3-ed22-477c-b099-212cb205cbb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-f6hhmpiuub4a']</value>
      <webElementGuid>a83d9543-a03a-4080-bf5d-edd30795c765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-login']/div/div/iframe</value>
      <webElementGuid>e185c561-26b0-49f0-9e39-e7ba112a6107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0e678839-59f6-4310-8a57-7e4c82193a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-f6hhmpiuub4a' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcCBsYoAAAAAH229CaA_zpClCyFwuqQXZ9M5EmT&amp;co=aHR0cHM6Ly9iZWJlY2x1Yi5leWRlbmRpZ2l0YWwuY28uaWQ6NDQz&amp;hl=id&amp;v=u-xcq3POCWFlCr3x8_IPxgPu&amp;theme=light&amp;size=normal&amp;cb=b1tjqahjrhfc']</value>
      <webElementGuid>3ecd0009-fb02-48a1-b63e-5801827e92e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
