<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Referal_syarat-form</name>
   <tag></tag>
   <elementGuidId>99ad1a88-5320-4cf0-aa7c-c6bf2d4f58d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#syarat-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='syarat-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cbcf169-9dad-492d-8925-35fc4f6296a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>262f902d-bcbb-4a4d-a431-b5881e44284f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>syarat-form</value>
      <webElementGuid>30ed655b-b6ea-4192-9e22-dd23882b5ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;syarat-form&quot;)</value>
      <webElementGuid>69c45dd0-a5ed-42fe-ae23-95d548ebbbc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='syarat-form']</value>
      <webElementGuid>6f8a953a-b835-4092-9b29-7b35f3963bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/div/input</value>
      <webElementGuid>d1ba8af5-44de-44f9-bbe2-e846b43b926f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>d51dda27-0328-4435-899a-6fe9a10c6039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'syarat-form']</value>
      <webElementGuid>1712274f-8efd-41ff-8529-cc7b13b80895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
