<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pass-form</name>
   <tag></tag>
   <elementGuidId>35c92f03-be9b-4aa8-ac24-6ff997f2c2d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b18d9876-56f3-497b-9c9b-e23508a07daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7131bcbd-08bf-40a7-9a7e-c93bcf74c49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pass-form</value>
      <webElementGuid>28837a62-8f47-4a03-b3e8-76d0a4df7c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_password</value>
      <webElementGuid>b4e792ae-8b1f-4115-8b7a-01f6efc7f395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kata Sandi Anda</value>
      <webElementGuid>5f391e4a-9625-455e-a508-4309543bfec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_password&quot;)</value>
      <webElementGuid>dab9ba22-f14e-4a6c-8f90-75c13311c39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_password']</value>
      <webElementGuid>0320268d-acfe-4f1a-bd13-b82872d2b211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-register']/form/div/div[4]/input</value>
      <webElementGuid>103f94ef-7a68-436f-8bd3-dc890e204bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>c5d3d6be-5b94-415a-a0e2-6dff61fa09d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pass-form' and @id = 'input_password' and @placeholder = 'Masukkan Kata Sandi Anda']</value>
      <webElementGuid>65772af9-006f-48f8-88b4-6d0ed846a7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
