<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir Anak_datepickers-form</name>
   <tag></tag>
   <elementGuidId>91f53d83-26ee-49c4-b5af-20523c360a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e8cbc4a-d498-4fd5-b253-02d175d023db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>055cf09e-5024-4732-9e0c-aa9eea893921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-calendar</value>
      <webElementGuid>590b88a8-b42f-45ad-bb30-dd94bf5cf6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickers-form</value>
      <webElementGuid>9f5ba3b5-a081-46f1-b0a5-300f1e0ac1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepick-form</value>
      <webElementGuid>97b43ca7-2755-4d80-befc-e31904097cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 14-02-2020</value>
      <webElementGuid>61297b06-b03d-42d9-8755-b7d3481be227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>04f7a665-1873-44d8-9135-aa64ead635dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>2d57d15f-f021-4d7a-8ff3-bc011d009af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg-calendar&quot;)</value>
      <webElementGuid>84403e61-0b2e-4ad7-8845-b64d05cd1f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-calendar']</value>
      <webElementGuid>eab1c31d-768d-4a43-a609-3642f544e59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggal_lahir_anak_regist-form']/input</value>
      <webElementGuid>9f595b94-f70b-4474-a805-cc8bec3bb0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>a44855ac-db3c-4896-b467-faa05a83dc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reg-calendar' and @name = 'datepickers-form' and @placeholder = 'Contoh: 14-02-2020']</value>
      <webElementGuid>aadf05a7-67ae-4456-9dc1-d183f7a10568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
