<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>formDOBAnak</name>
   <tag></tag>
   <elementGuidId>282708a7-b33c-4b3c-95e4-0c9a7b2eec7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-calendar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reg-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acd13f80-a9dd-40bf-9b8d-21a510813929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93d08226-b31d-4ae0-9e22-98a97f3c9650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-calendar</value>
      <webElementGuid>b34b6143-ce28-4688-b7b6-a1718c45e39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickers-form</value>
      <webElementGuid>31364d7a-a2cb-43cf-a4e2-3eb03a602c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-valid</value>
      <webElementGuid>1d65f15f-02b1-44e3-a551-020a3a889c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 2019-02-22</value>
      <webElementGuid>e0d722c6-92cb-4c8e-b5c7-190831b3300e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5c75c2d1-49e8-4a9f-a812-49ffb31b217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg-calendar&quot;)</value>
      <webElementGuid>1873b7b9-a09b-4f7f-8ea2-e9aae6c39ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-calendar']</value>
      <webElementGuid>9cd62e9e-f006-48d2-ab48-817efe436042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggal_lahir_anak_regist-form']/input</value>
      <webElementGuid>c9ae1c85-429c-4baf-a9cf-5710e878f206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>8514230f-9b10-458f-941e-d697b86c19db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reg-calendar' and @name = 'datepickers-form' and @placeholder = 'Contoh: 2019-02-22']</value>
      <webElementGuid>55860c95-d271-43ee-a2ca-7f2b1055b355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
