<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_full-name-form</name>
   <tag></tag>
   <elementGuidId>7ff96b28-db34-44dd-817c-af67b4f50bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='full-name-form']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;full-name-form&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71153a5d-2003-43b5-ab2d-700b648e86a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f605c5ce-0719-411a-8074-79dc3e315e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>full-name-form</value>
      <webElementGuid>5d48550e-dbbc-4ed7-a533-35cd81e8f75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a096a48b-a903-4929-8f3e-355594ae7008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Lengkap Anda Disini</value>
      <webElementGuid>4c05ef2c-467f-4dff-aea4-17eb6233a718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e746ecb-59cf-4ede-a616-4f689a86171a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;section-register&quot;]/div[@class=&quot;regist-identity&quot;]/div[@class=&quot;regist-identity_iner&quot;]/form[@class=&quot;form-regist&quot;]/div[@class=&quot;regist-identity_bodyform&quot;]/div[@class=&quot;regist-identity_bodyform_item&quot;]/input[1]</value>
      <webElementGuid>a9e2d72c-4e06-43f7-9f51-ce7a7bdecfa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='full-name-form']</value>
      <webElementGuid>335ed05b-a002-4378-ba47-5545b509f525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>685cd91c-00ec-4269-98c8-2bd548fba8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'full-name-form' and @placeholder = 'Masukkan Nama Lengkap Anda Disini']</value>
      <webElementGuid>42dc6686-c770-469c-8cbd-4333375c1c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
