<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password_konfirmasipass-form</name>
   <tag></tag>
   <elementGuidId>37b70dd6-bea7-46fb-b90b-1783c720677f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;konfirmasipass-form&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='konfirmasipass-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce4778d9-98db-41a5-be72-33245d107861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5c4eb806-0914-403c-b885-ab6b53fa355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>konfirmasipass-form</value>
      <webElementGuid>1fe20439-5354-4c86-9900-15d23d507482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Konfirmasi Kata Sandi Anda</value>
      <webElementGuid>871671ac-5b73-405f-add8-ce1866d42a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;section-register&quot;]/div[@class=&quot;regist-identity&quot;]/div[@class=&quot;regist-identity_iner&quot;]/form[@class=&quot;form-regist&quot;]/div[@class=&quot;regist-identity_bodyform&quot;]/div[@class=&quot;regist-identity_bodyform_item&quot;]/input[1]</value>
      <webElementGuid>ea7f5219-c82d-45cc-854b-d884e360daa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='konfirmasipass-form']</value>
      <webElementGuid>00e1c688-6712-4eff-a628-52bf168bf2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>c0d2d05c-a7f5-4d10-b3f3-4bd957d24bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'konfirmasipass-form' and @placeholder = 'Masukkan Konfirmasi Kata Sandi Anda']</value>
      <webElementGuid>f4805e5f-9ec0-489a-9e35-c8dc6e788d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
