<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arrow Kiri</name>
   <tag></tag>
   <elementGuidId>0520dfe6-3b23-4a64-9cfb-20015839f51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.img-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c7da0ae-1836-440f-b883-3802c5c59089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-arrow</value>
      <webElementGuid>8545322f-0978-447a-8264-95112ea2c044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pimcore_area_landing-article-list pimcore_area_content&quot;]/div[@class=&quot;article-milestone&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;new-milestone&quot;]/div[@class=&quot;milestone-new swiper-container swiper-container-initialized swiper-container-horizontal swiper-container-pointer-events&quot;]/div[@class=&quot;milestone-arrow&quot;]/div[@class=&quot;milestone-prev swiper-button-disabled&quot;]/div[@class=&quot;img-arrow&quot;]</value>
      <webElementGuid>61b294db-0a2d-4408-bda2-2b4f497f8aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div</value>
      <webElementGuid>a03c4a1f-b6de-403a-97e6-5ef2f2f9ab5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
