<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Depan_first-name-form</name>
   <tag></tag>
   <elementGuidId>89241ad5-2bbb-4444-9125-bc4dbab9f19b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;first-name-form&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='first-name-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>896b63a3-99fd-4e90-a6b9-25fead28e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3880482d-fedd-4ff0-af9e-3f7b3cc420ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first-name-form</value>
      <webElementGuid>d233531f-e945-4108-a1ff-9f584bef36d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1f0c6efc-1515-499e-ad6e-872d55d320f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Depan Anda Disini</value>
      <webElementGuid>50d9fe53-0e7e-4391-af0b-1cb8c86cb848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5a10760-aa2b-4261-a44f-ff58c2d4ba20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;section-register&quot;]/div[@class=&quot;regist-identity&quot;]/div[@class=&quot;regist-identity_iner&quot;]/form[@class=&quot;form-regist&quot;]/div[@class=&quot;regist-identity_bodyform&quot;]/div[@class=&quot;regist-identity_bodyform_item&quot;]/input[1]</value>
      <webElementGuid>28700e66-3c66-4b25-8a46-7cbddc20e23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='first-name-form']</value>
      <webElementGuid>1de5975c-c587-4442-a7c8-f154a54e178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>788c1589-a468-4c3e-9ea0-49db05655ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'first-name-form' and @placeholder = 'Masukkan Nama Depan Anda Disini']</value>
      <webElementGuid>3d1875dc-72ba-4852-bca8-16aca28d2d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
