<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close popup</name>
   <tag></tag>
   <elementGuidId>5795b501-73fa-4c45-bd7e-efa0d803331f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>545dc734-4fc7-455c-9d02-1049b46a46c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>43bd97e5-9c29-47af-8b49-9e99827707f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>3507093139</value>
      <webElementGuid>8fbb689a-3b36-4a7f-8107-ca9f1e380a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/x.png</value>
      <webElementGuid>1d4debd7-5e57-4a24-8271-75330c339019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;pagespeed.lazyLoadImages.loadIfVisibleAndMaybeBeacon(this);</value>
      <webElementGuid>e6c52a8f-ff64-4492-bab7-c3bc0b1472e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;modal-sukses-otp-form show&quot;]/div[@class=&quot;modal-sukses-otp-form_iner&quot;]/div[@class=&quot;modal-sukses-otp-form_close&quot;]/img[1]</value>
      <webElementGuid>990ca377-61fc-442c-970a-abf9d1996de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>486472c5-c4ba-4c53-bb6e-558561578510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>e9419d53-4770-4b75-85a6-83fe74bfb9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'close' and @src = '/assets/images/x.png']</value>
      <webElementGuid>ada51308-f681-4135-8b19-9ab83ffe768e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
