<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text Penulis</name>
   <tag></tag>
   <elementGuidId>5ae9683b-9959-4151-981e-c5eb9a20a275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Penulis'])[1]/following::p[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>da451922-abf1-4011-aa80-a053ab606ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penulis</value>
      <webElementGuid>3f26de0b-c808-48ee-9421-d2446f6fa623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;hero-contributor&quot;]/div[@class=&quot;hero-contributor__container&quot;]/div[@class=&quot;row profiledesc&quot;]/div[@class=&quot;col-12 col-md-12 sol-sm-12 col-lg-6 col-xl-6&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;hero-contributor__info&quot;]/div[1]/p[1]</value>
      <webElementGuid>61a0b3e6-cb1e-4de3-ae35-0025c46e2226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Penulis'])[1]/following::p[1]</value>
      <webElementGuid>a7f60028-d71c-48fa-9d63-d7590a1cebc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::p[1]</value>
      <webElementGuid>098ecd06-ed2e-4a0c-8d0a-3a275c021bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mauliyana Puspa Adityasari'])[1]/preceding::p[1]</value>
      <webElementGuid>e0e5ec03-2b2b-4db6-b421-b3f78a52b152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Profesional >'])[1]/preceding::p[1]</value>
      <webElementGuid>69b59f41-172e-49dd-9b1a-1c12f39f4b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penulis']/parent::*</value>
      <webElementGuid>83f0e1b8-e17f-4061-9d43-10a8fc4bb805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>8a1db1f2-9560-4fe6-bef0-fedc3880f1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Penulis' or . = 'Penulis')]</value>
      <webElementGuid>9dce4665-97f9-41b4-b80f-a7555b047349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
