<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proses Editorial Button Lebih Sedikit</name>
   <tag></tag>
   <elementGuidId>3a6300b3-bdef-4ef0-9230-34f308d18c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='readMore(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-more-less-view</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5be1f69-f973-4c53-bac4-527296e77685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>c1f2b14c-80a6-4723-9852-ee5cafc75347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-more-less-view</value>
      <webElementGuid>688a9264-877b-45f1-9a4c-f1f3f742eba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>readMore(this)</value>
      <webElementGuid>b8b18df5-febe-45f1-b043-c219e0bb460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lebih Sedikit </value>
      <webElementGuid>a5467944-e89f-4e63-96cd-f77dd0ebb852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eeat-editorial&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 headline&quot;]/div[@class=&quot;morelessview&quot;]/button[@class=&quot;btn-more-less-view&quot;]</value>
      <webElementGuid>e497a8f1-8bfe-4e9d-aae3-17cb9c090c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='readMore(this)']</value>
      <webElementGuid>c00b4f9f-c035-4b88-8a28-78b7337fd337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='eeat-editorial']/div[2]/div/div/div[4]/button</value>
      <webElementGuid>3d00c68d-e32e-4122-9efb-ca7e8127649b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memastikan tim internal Bebeclub ikut serta dalam setiap proses yang telah disebutkan di atas.'])[1]/following::button[1]</value>
      <webElementGuid>d897870c-90ab-410c-a29a-2afb4a654999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setiap artikel memiliki tanggal dan waktu penerbitan.'])[1]/following::button[1]</value>
      <webElementGuid>12fc3cfb-841a-494b-8a22-a91394bf2103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel Terbaru'])[1]/preceding::button[1]</value>
      <webElementGuid>a5bc7330-ba76-4eba-82d2-99214c6d1cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tumbuh Kembang'])[3]/preceding::button[1]</value>
      <webElementGuid>427791b6-6a9b-4075-bc99-d8ae90f26c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lebih Sedikit']/parent::*</value>
      <webElementGuid>ad84cb12-4e3b-4db2-8a27-17c98b48a921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a3d681a7-96ad-4501-ad51-8d6376e01101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = 'javascript:' and (text() = 'Lebih Sedikit ' or . = 'Lebih Sedikit ')]</value>
      <webElementGuid>ed6b5219-c79e-4fc7-a745-138458501d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
